// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaamibpwyzqcixgxmfzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhYW1pYnB3eXpxY2l4Z3htZnp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDgwMTQsImV4cCI6MjA2MTQyNDAxNH0.oComJn5zKiPN7jNAdq0AjqyqlrdERnFm5s2WjUl-SSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);